### PR TITLE
feat(tutorial): complete step 1

### PR DESCRIPTION
**Pull request by wlhenson**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by tw15egan** [comment]
Hey @wlhenson , it looks like you're PR-ing from your master branch, and not your `react-step-1` brnach

**Comment by wlhenson** [comment]
@tw15egan  Could you assist me with fixing this?  I got to the end of the course and then noticed that the PR for step 1 had issues.  I'm not sure how to get this fixed.

**Comment by wlhenson** [comment]
Is there a way to discard a pull request and start over?

**Comment by wlhenson** [comment]
I forced a push and created a new PR.  Closing.

**Pull request closed without merging**
