### PR TITLE
feat: add react-step-2

### PR DESCRIPTION
**Pull request by emyarod**
This PR adds a landing page and repos page with a static sidebar and data table. Also uses React Router `<Link>` for routing

### CODE REVIEW

**Comment by mattrosno** [comment]
This left alignment looks off.
image

What's the plan with all this below? I thought this was going to be assembled in a later step? Where step 2 stopped at the tab container?
image

Image could be 2x retina quality.
image

Missing space between top of data table and UI shell.
image

**Comment by mattrosno** [comment]
Can we `max-width:100%` on the image so it scales on small viewports?

**Comment by mattrosno** [comment]
Can't click "Repo 1". It won't check.
image

**Comment by emyarod** [comment]
all points should be addressed now

**Pull request merged**
