### PR TITLE
feat(tutorial): complete step 1

### PR DESCRIPTION
**Pull request by Mike-Wendel**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by kellychurchill** [comment]
👍 Looks good - 🎉 You are one step closer to completion of the Carbon React tutorial and earning the digital credential.

**Comment by Mike-Wendel** [comment]
@kellychurchill Applying for my badge now, but it looks like this PR never got 'approved'. Its closed, and your closing comment looks like approval, but I don't see the 'Approved' flag anywhere. 

🤔 Is that going to stop the badging process? Is there something more that needs to be done, or is this one okay? 

Thanks!

**Comment by kellychurchill** [comment]
@Mike-Wendel Nope you're all good

**Comment by Mike-Wendel** [comment]
@kellychurchill Thank you.  👍

**Pull request closed without merging**
