### PR TITLE
feat(tutorial): complete step 1 - Cambridge

### PR DESCRIPTION
**Pull request by paula242242**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by paula242242** [comment]
@RoystonS - I removed my `yarn.lock` file and tried to re-run `yarn` a couple of times but came up against the same issue - the connection keeps timing out.  Is it worth me just removing everything and starting again?

**Comment by RoystonS** [comment]
No, I can't imagine how that would help, and it would take a load of your time.

It _might_ be interesting to make a new folder, copy your `package.json` file into that, and try `yarn` there.  That would _literally_ remove everything and try with everything fresh.  If that works, something weird is going on, and I'll come and have a look. If that doesn't work, something weird is going on, and I'll come and have a look. ;-)

**Comment by paula242242** [comment]
Perhaps we will go with you having a look! I tried a running yarn from a clean folder with a copy of my `package.json` and still get the same error!

**Comment by paula242242** [comment]
@RoystonS - magic happened this morning, I tried running `yarn` again and it worked!! Pushed up the new `yarn.lock` file and the checks have all passed......how weird!

**Pull request closed without merging**
