### PR TITLE
feat(tutorial): complete step 5 (BOE)

### PR DESCRIPTION
**Pull request by daniel-m-s**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by ZrianinaMariia** [comment]
@daniel-m-s  Looks great based on the committed files and Netlify preview. However, http://carbon-tutorial-daniel-m-s.mybluemix.net/#/ route gives me 404. Could you please specify the url to take a look at your deployment?

**Comment by daniel-m-s** [comment]
@ZrianinaMariia, I deployed in Frankfurt not Dallas. Go to http://carbon-tutorial-daniel-m-s.eu-de.mybluemix.net/#/

**Comment by ZrianinaMariia** [comment]
@daniel-m-s Fantastic 🥇!  I've recorded your completion of step 5.

**Comment by ZrianinaMariia** [comment]
@daniel-m-s Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Pull request closed without merging**
