### PR TITLE
feat(tutorial): complete step 1

### PR DESCRIPTION
**Pull request by vladbalanescu**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by vladbalanescu** [comment]
@alisonjoseph Done, can you please have another look?

**Comment by vladbalanescu** [comment]
@alisonjoseph Any updates on this one?

**Comment by vladbalanescu** [comment]
@kellychurchill Do you please mind having a look at my last PR too? I just need this one in to apply for the badge

**Comment by mattrosno** [comment]
@vladbalanescu Netlify didn't trigger a re-build of this PR's deploy preview, but your change to Sass import looks good!

**Pull request closed without merging**
