### PR TITLE
React step 4

### PR DESCRIPTION
**Pull request by krekalidis**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by krekalidis** [comment]
Hi @kellychurchill 

This pull request is for step 4, not for step 5.

**Comment by kellychurchill** [comment]
@krekalidis - the preview link is labeled step 5 because it is the expected outcome at the start of step 5. 

Your preview does not match because the third word  in each title phrase is not correctly formatted - see the instructions here: https://www.carbondesignsystem.com/tutorial/react-step-4#type

**Comment by krekalidis** [comment]
@kellychurchill - I made the appropriate changes.

**Comment by kellychurchill** [comment]
👍 Looks good - 🎉 You are one step closer to completion of the Carbon React tutorial and earning the digital credential.

**Pull request closed without merging**
