### PR TITLE
feat(tutorial): complete step 5 + from SH Bryan

### PR DESCRIPTION
**Pull request by supermqB**
Closes #

the URL on IBM cloud.

https://carbon-tutorial-yinwenb.eu-gb.mybluemix.net/

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by kellychurchill** [comment]
@supermqB Per instructions in the tutorial step 5, please include your mybluemix.net URL for your deployed app in your pull request description.

**Comment by supermqB** [comment]
Kelly,

Here is the link where I deployed the carbon-tutorial on IBM cloud. Please help to process the PR.

https://carbon-tutorial-yinwenb.eu-gb.mybluemix.net/

**Comment by supermqB** [comment]
You may tried to access the deployed app from US endpoint. but we can't apply the space on it from China mainland. Sorry for inconvenience.

**Comment by supermqB** [comment]
@kellychurchill Can you help to process the PR, then issue the badge to me. I've submit the application form last week.
Thanks very much.

**Pull request closed without merging**
