### PR TITLE
feat(tutorial): complete step 2 (Boeblingen)

### PR DESCRIPTION
**Pull request by Brenne**

### CODE REVIEW

**Comment by ZrianinaMariia** [comment]
@Brenne Almost there! 

Your preview does not look like the preview from the tutorial: https://react-step-3--carbon-tutorial.netlify.com/#/. I can see couple of scss classes are missing. 

Please try again.

**Comment by Brenne** [comment]
@ZrianinaMariia I've the tutorial has been updated since last time, so I started from scratch. Now it looks the same apart from the vertical divider in the header but this seems to come out of carbon.

**Comment by ZrianinaMariia** [comment]
> @ZrianinaMariia I've the tutorial has been updated since last time, so I started from scratch. Now it looks the same apart from the vertical divider in the header but this seems to come out of carbon.

Yes, there is some style difference between carbon 10.2 and carbon 10.3 like vertical divider in the header and typography in the UI shell, etc 👍

**Comment by ZrianinaMariia** [comment]
@Brenne Looks fantastic 🏆! I've recorded your completion of step 2.

**Pull request closed without merging**
