### PR TITLE
feat(tutorial): complete step 4

### PR DESCRIPTION
**Pull request by andreabaader**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by andreabaader** [comment]
@kellychurchill  I think I did what the tutorial said about creating the new branch for step 4:
_$ git fetch upstream
$ git checkout -b react-step-4 upstream/react-step-4_

I see the note in the tutorial. 
_Note: This builds on top of step 3, but be sure to check out the upstream step 4 branch because it includes the static assets required to get through this step._

**So do I need to call another git command besides the two above?**

**Comment by kellychurchill** [comment]
When you view your preview, the last word in the 3 phrases are not bold. This is because the code you have in this commit contains changes from step 3. 

I would suggest starting fresh in a new directory.

**Comment by andreabaader** [comment]
@kellychurchill Hi Kelly, please check again on https://deploy-preview-1430--carbon-tutorial.netlify.com.
It should look ok.

**Comment by kellychurchill** [comment]
👍 Looks good - 🎉 You are one step closer to completion of the Carbon React tutorial and earning the digital credential.

**Pull request closed without merging**
