### PR TITLE
feat(tutorial): complete step 5

### PR DESCRIPTION
**Pull request by shadab**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by shadab** [comment]
@alisonjoseph https://carbon-tutorial-shadab.eu-gb.mybluemix.net/#/

**Comment by shadab** [comment]
@alisonjoseph Any chance you can take a look now?

**Comment by mattrosno** [comment]
There look to be some styling issues, as the image should be right-aligned in the tab content.
image

**Comment by shadab** [comment]
@mattrosno @alisonjoseph Would you mind taking another look - https://carbon-tutorial-shadab.eu-gb.mybluemix.net/#/

image

**Comment by shadab** [comment]
Just wondering if @mattrosno @alisonjoseph would mind taking another look - https://carbon-tutorial-shadab.eu-gb.mybluemix.net/#/

**Pull request closed without merging**
