### PR TITLE
feat(tutorial): complete step 4

### PR DESCRIPTION
**Pull request by zrehmani**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by zrehmani** [comment]
This is step-4 (not step-1).  Also like the last step, I had the same issues compiling.  With yarn and yarn start, compiler complained there is no carbon-icons package.  So I added that and upgraded all packages.  It seems to work fine after that.  Build matches preview exactly.  Let me know if there are any issues you see.

**Comment by alisonjoseph** [comment]
@zrehmani The repositories link on the preview url doesn't seem to be loading.

**Comment by zrehmani** [comment]
> @zrehmani The repositories link on the preview url doesn't seem to be loading.

That's strange - seems to load just fine for me.
https://deploy-preview-4760--carbon-tutorial.netlify.app

**Comment by zrehmani** [comment]
> @zrehmani The repositories link on the preview url doesn't seem to be loading.

I am not sure what I should do to get this approved to move to the next chapter.  The preview link opens for me correctly.  Do I need to do another pull request? Please advice.

**Comment by alisonjoseph** [comment]
When I click the "repositories" link in your preview url I see a blank white page, there should be a table view like the preview here https://react-step-5--carbon-tutorial.netlify.app/#/repos

**Comment by zrehmani** [comment]
ok i see the problem - once I fix it do I have to create a new pull request?

**Comment by zrehmani** [comment]
I have made the fixes and committed changes.  Let me know if there is anything else I can do.

**Comment by zrehmani** [comment]
Hi there - I have updated the files and the repository section works fine now.  Circle CI is failing for some reason to load the carbon icon package.  I had to install this package locally because the branch would not compile without it.  Let me know what I need to do in order to get this step approved.  Thank you!

**Comment by zrehmani** [comment]
@alisonjoseph can you please look at my pull request and see if everything looks good so it can be approved.  Thank you!

**Pull request closed without merging**
