### PR TITLE
feat(tutorial): complete step 5 - Beer Sheva

### PR DESCRIPTION
**Pull request by barhaim**
https://carbon-tutorial-barhaim.mybluemix.net

### CODE REVIEW

**Comment by barhaim** [comment]
@kellychurchill 
https://carbon-tutorial-barhaim.mybluemix.net

**Comment by kellychurchill** [comment]
@barhaim Your layout does not match the expected outcome. Please have a look at your styles and commit your updates to this PR and update your app on IBM Cloud

**Comment by barhaim** [comment]
@kellychurchill 
I fixed it! 
carbon-tutorial-barhaim.mybluemix.net

**Comment by barhaim** [comment]
fixed 
https://github.com/carbon-design-system/carbon-tutorial/pull/1227
http://carbon-tutorial-barhaim.mybluemix.net
 

                                                                        Regards,                         

                        BAR HAIM                        CCoE Member                                                                                                
                                                                                                                                Phone: 972-074-7375125 | Mobile: 972-0504213370                        E-mail: BARHA@il.ibm.com                        Cyber Center of Excellence: www.research.ibm.com/haifa/ccoe/                        Find me on:                           Helkike Haour 16 Park Gav Yam Negev                        Be'er Sheva, D 8470912                        Israel                        
 
 
----- Original message -----From: Kelly Churchill <notifications@github.com>To: carbon-design-system/carbon-tutorial <carbon-tutorial@noreply.github.com>Cc: Bar Haim <barha@il.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [carbon-design-system/carbon-tutorial] feat(tutorial): complete step 5 - Beer Sheva (#1227)Date: Wed, Jul 3, 2019 8:36 PM 
@barhaim Your layout does not match the expected outcome. Please have a look at your styles and commit your updates to this PR and update your app on IBM Cloud
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by kellychurchill** [comment]
👍  Looks good! 
Feel free to stop this running application on IBM Cloud to avoid the possibility of incurring any charges 💵

**Pull request closed without merging**
