### PR TITLE
React step 5 - Hursley!

### PR DESCRIPTION
**Pull request by winslet**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by winslet** [comment]
Its alive! https://carbon-tutorial-winslet.mybluemix.net/#/

**Comment by winslet** [comment]
Question for whomever reviews this: Why does my API key still upload even though the `.env` is in the gitignore?

**Comment by ind1go** [comment]
Eek! It'll be because you `git add`ed the `.env` file before you altered the `.gitignore` file. Please go to http://github.com/settings/tokens and remove your token to invalidate it and prevent anyone else using it.

The intent is that you add your token to `.env.local`, which was ignored right from the initial `.gitignore` file.

**Comment by winslet** [comment]
Have removed my token, thats an interesting way of working, every day is a school day! Thanks @ind1go

**Comment by ind1go** [comment]
Oh, could you put a new token in your env.local and re-push? The cloud app doesn't work now (which is good!).

**Comment by winslet** [comment]
ugh so ive updated it to remove the key, im still getting emails like this

image

Which is wrong, and now the app is failing to build. Have I removed too much in the .gitignore? I added `.env` which seemed to work but now is breaking everything. SIGH.

**Comment by ind1go** [comment]
Ah yeah, you've gone a bit overboard with the deletion. You need the `.env` file back because it had [this content](https://github.com/carbon-design-system/carbon-tutorial/blob/3daa6d3ba594c5dfc4b1a795664a5ad4b1490206/.env) which allows the SASS to compile. 

First though, remove the line you added to `.gitignore` to ignore `.env` as you _do_ want `.env` checked in, you just don't want your personal stuff in `.env.local` checked in.

I would:
1. Change `.gitignore`
1. `git add` the change to `.gitignore`
1. Recreate `.env` with the prior content in it
1. Add your new GitHub access token (neither of the ones you previously used - remove those from GitHub) to `.env.local`. Doing `git status` shouldn't offer to commit this because it should be being ignored.
1. Check that `cf push` works again
1. Commit and push to GitHub!

**Comment by winslet** [comment]
Woo, think ive done it 👍 works locally and on the generated link :)

**Comment by ind1go** [comment]
Cool, I just need you to `cf push` it again so I can check - the one up there has invalid credentials.

**Comment by lee-chase** [comment]
Looks like you had some fun.

:+1::skin-tone-2:  go ahead and claim your badge and t-shirt.

**Pull request closed without merging**
