### PR TITLE
React step 4 boe

### PR DESCRIPTION
**Pull request by rblath**

### CODE REVIEW

**Comment by ZrianinaMariia** [comment]
@rblath Almost there! There are some styling differences, e.g. font, spacing, separation line is missing https://react-step-5--carbon-tutorial.netlify.com/#/

**Comment by ZrianinaMariia** [comment]
@rblath Looks way better! The only thing that is left is fixing the font for the last (bold) word in the header.

**Comment by rblath** [comment]
I have fixed the problems. Please check again, thanks.

**Comment by rblath** [comment]
I think I've got it now. Can you check please?

**Comment by ZrianinaMariia** [comment]
@rblath Looks great now 💯! I've recorded your completion of step 4.

**Pull request closed without merging**
