### PR TITLE
feat(tutorial): complete step 3 -- Ottawa

### PR DESCRIPTION
**Pull request by mcardin2**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by mcardin2** [comment]
test this please

**Comment by mcardin2** [comment]
Commits failing with:
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

**Comment by mcardin2** [comment]
@kellychurchill.  Passing now.  Needed to add the apollo plugins into package.json rather than installing them globally.  You might want to update the tutorial instructions for that step.

**Comment by kellychurchill** [comment]
👍 Looks good - 🎉 You are one step closer to completion of the Carbon React tutorial and earning the digital credential.

**Pull request closed without merging**
