### PR TITLE
feat(tutorial): complete step 2

### PR DESCRIPTION
**Pull request by Lucinda94**
Completed step 2

### CODE REVIEW

**Comment by Lucinda94** [comment]
@kellychurchill Hi, could you let me know what I have done wrong here please?

**Comment by kellychurchill** [comment]
@mattrosno can you help @Lucinda94 with this?

**Comment by mattrosno** [comment]
@alisonjoseph @tw15egan the Netlify error is:

```
8:14:48 AM: Creating an optimized production build...
8:14:50 AM: Failed to compile.
8:14:50 AM: 
8:14:50 AM: ./src/index.js
8:14:50 AM: Error: [BABEL] /opt/build/repo/src/index.js: Cannot find module 'gensync' (While processing: "/opt/build/repo/node_modules/babel-preset-react-app/index.js")
8:14:50 AM: error Command failed with exit code 1.
```

Do you know the recommended fix for this?

**Comment by Lucinda94** [comment]
> @alisonjoseph @tw15egan the Netlify error is:
> 
> ```
> 8:14:48 AM: Creating an optimized production build...
> 8:14:50 AM: Failed to compile.
> 8:14:50 AM: 
> 8:14:50 AM: ./src/index.js
> 8:14:50 AM: Error: [BABEL] /opt/build/repo/src/index.js: Cannot find module 'gensync' (While processing: "/opt/build/repo/node_modules/babel-preset-react-app/index.js")
> 8:14:50 AM: error Command failed with exit code 1.
> ```
> 
> Do you know the recommended fix for this?

**Comment by Lucinda94** [comment]
> @alisonjoseph @tw15egan the Netlify error is:
> 
> ```
> 8:14:48 AM: Creating an optimized production build...
> 8:14:50 AM: Failed to compile.
> 8:14:50 AM: 
> 8:14:50 AM: ./src/index.js
> 8:14:50 AM: Error: [BABEL] /opt/build/repo/src/index.js: Cannot find module 'gensync' (While processing: "/opt/build/repo/node_modules/babel-preset-react-app/index.js")
> 8:14:50 AM: error Command failed with exit code 1.
> ```
> 
> Do you know the recommended fix for this?

@mattrosno 
I can see that my step 1 failed to deploy a preview with the same error but was approved, and I've looked at the last PR for a step 2 from someone else which also failed to deploy a preview with the same error but their PR got approved and closed, I also checked out quite a few closed PRs which also failed to deploy a preview but still approved. Is there any reason why mergify isn't working?

**Comment by tw15egan** [comment]
Not quite sure what's going on, everything builds fine locally and no missing `.yarn-offline-mirror` files. Seems like an error on Netlify's end. Clearing cache and redeploying via Netlify UI seems to fix all builds.

**Comment by Lucinda94** [comment]
> Not quite sure what's going on, everything builds fine locally and no missing `.yarn-offline-mirror` files. Seems like an error on Netlify's end. Clearing cache and redeploying via Netlify UI seems to fix all builds.

Hey @tw15egan, I don't think Mergify is working either. I can see that since my step 1 was approved and closed no other branch merges have seen the mergify bot.

**Pull request closed without merging**
