### PR TITLE
React step 2

### PR DESCRIPTION
**Pull request by jen-thach**
Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- Updated styling

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by jen-thach** [comment]
Hi Team, I have made this PR before and was told to fix up my styling as it did not match the preview. I have done this and it should match now. Please let me know if there are any other issues. Thanks!!

**Comment by tw15egan** [comment]
It looks like the Table is still not inside a grid row, so it's not spanning the entire page.

Here's what it should look like https://react-step-3--carbon-tutorial.netlify.app/#/repos

**Comment by jen-thach** [comment]
Hi @tw15egan, thanks for the response! I just pushed a commit that fixes the table. It should now span across the entire page.

**Comment by tw15egan** [comment]
Visually approved 👍

**Pull request closed without merging**
